from datetime import datetime, timezone

import streamlit as st

from lib import llm, routing
from lib.knowledge import AGENTS, RECORD_CATEGORIES, RECORDS_DIR

st.title(":material/chat: Ask the program")

bucket = st.session_state.selected_agent
st.session_state.chat_histories.setdefault(bucket, [])
exchanges = st.session_state.chat_histories[bucket]

SUGGESTIONS = {
    "auto": [
        "We found a soft spot during subgrade prep — what do we do?",
        "How often do we plate-load test a 하이셀 platform?",
        "What thickness do we need for a 50t crane on soft clay?",
    ],
    "platform-design": [
        "What thickness do we need for a 50t crawler crane on Cu=25kPa clay?",
        "Do we need 하이셀 or is aggregate-only OK here?",
    ],
    "platform-construction": [
        "What's the max lift thickness for compaction?",
        "How do we install 하이셀 geocell panels?",
    ],
    "platform-safety": [
        "There's a tension crack near the crest, 3m from our crane — what now?",
        "What edge distance do we need from an open excavation?",
    ],
    "site-safety": [
        "Draft today's safety briefing — subgrade compaction and geocell placement, sunny 32°C.",
        "What's the exclusion zone around the Pebble Mixer while it's running?",
        "What PPE do we need for placing and pinning geocell panels?",
    ],
    "platform-qaqc": [
        "What test do we need before opening a platform to crane traffic?",
        "What goes in an as-built handover package?",
    ],
}


def build_agent_history(agent_key: str, up_to: int | None = None) -> list[dict]:
    """Reconstruct this specialist's own message history — only the exchanges it was
    actually consulted on, so its context matches what a real dispatch would see."""
    msgs = []
    for exchange in exchanges[:up_to]:
        if agent_key in exchange["responses"]:
            msgs.append({"role": "user", "content": exchange["user_text"]})
            msgs.append({"role": "assistant", "content": exchange["responses"][agent_key]})
    return msgs


def save_draft_form(exchange_idx: int, agent_key: str, response_text: str) -> None:
    agent_label = AGENTS[agent_key]["label"]
    with st.expander("Save as draft record", icon=":material/save:"):
        with st.form(key=f"save_form_{bucket}_{exchange_idx}_{agent_key}"):
            category = st.selectbox("Category", RECORD_CATEGORIES, key=f"cat_{bucket}_{exchange_idx}_{agent_key}")
            default_name = f"{agent_key}-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}"
            filename = st.text_input("Filename (no extension)", value=default_name, key=f"fn_{bucket}_{exchange_idx}_{agent_key}")
            draft_banner = (
                f"> **STATUS: DRAFT — PENDING RESPONSIBLE ENGINEER'S REVIEW AND SIGN-OFF**\n"
                f"> Generated by the {agent_label} chat assistant "
                f"({datetime.now(timezone.utc).strftime('%Y-%m-%d')}). Not an approved record.\n\n"
            )
            content = st.text_area(
                "Content (editable before saving)",
                value=draft_banner + response_text,
                height=240,
                key=f"content_{bucket}_{exchange_idx}_{agent_key}",
            )
            if st.form_submit_button("Save draft", icon=":material/save:"):
                target_dir = RECORDS_DIR / category
                target_dir.mkdir(parents=True, exist_ok=True)
                target_path = target_dir / f"{filename}.md"
                if target_path.exists():
                    target_path = target_dir / f"{filename}-{datetime.now(timezone.utc).strftime('%H%M%S')}.md"
                target_path.write_text(content, encoding="utf-8")
                st.success(f"Saved to `{target_path.relative_to(RECORDS_DIR.parent)}`")


# --- Render prior exchanges ---
if not exchanges:
    st.pills("Try asking:", SUGGESTIONS.get(bucket, SUGGESTIONS["auto"]), key="suggestion_pill")
    if st.session_state.get("suggestion_pill"):
        st.session_state["_pending_prompt"] = st.session_state["suggestion_pill"]

for i, exchange in enumerate(exchanges):
    with st.chat_message("user"):
        st.write(exchange["user_text"])
    for agent_key, text in exchange["responses"].items():
        avatar = AGENTS[agent_key]["icon"]
        with st.chat_message("assistant", avatar=avatar):
            st.caption(f"**{AGENTS[agent_key]['label']}**")
            st.write(text)
            save_draft_form(i, agent_key, text)

# --- Handle new input ---
prompt = st.chat_input("Ask a question", submit_mode="disable")
if not prompt and st.session_state.get("_pending_prompt"):
    prompt = st.session_state.pop("_pending_prompt")

if prompt:
    if bucket == "auto":
        agents_to_ask = routing.route(prompt)
    else:
        agents_to_ask = [bucket]

    with st.chat_message("user"):
        st.write(prompt)

    if bucket == "auto" and routing.is_hazard(prompt):
        st.warning(
            "This looks like it may describe an active hazard — routing to Safety first.",
            icon=":material/warning:",
        )

    api_key = llm.get_api_key()
    new_exchange = {"user_text": prompt, "responses": {}}
    exchanges.append(new_exchange)

    for agent_key in agents_to_ask:
        avatar = AGENTS[agent_key]["icon"]
        with st.chat_message("assistant", avatar=avatar):
            st.caption(f"**{AGENTS[agent_key]['label']}**")
            history = build_agent_history(agent_key, up_to=len(exchanges) - 1)
            history.append({"role": "user", "content": prompt})
            full_text = st.write_stream(llm.stream_agent_reply(agent_key, history, api_key))
            new_exchange["responses"][agent_key] = full_text
            save_draft_form(len(exchanges) - 1, agent_key, full_text)

    st.rerun()
