from datetime import date, datetime, timezone

import streamlit as st

from lib import llm
from lib.knowledge import AGENTS, RECORD_CATEGORIES, RECORDS_DIR

AGENT_KEY = "site-safety"
EQUIPMENT_OPTIONS = [
    "Roller / compactor",
    "Excavator",
    "Pebble Mixer (on-site aggregate blending)",
    "Crane",
    "Dump trucks",
    "Hand tools / geocell pinning tools",
]

st.title(":material/shield_person: Daily safety document")
st.caption(
    "Fill in today's conditions and the Site Safety specialist drafts the toolbox talk / daily "
    "safety briefing — PPE, general site hazards, and equipment safety. Platform-specific hazard "
    "items (exclusion zones, active holds) are cross-referenced from Safety records, not invented "
    "here — check the Site status page or ask Safety directly for those."
)

st.session_state.setdefault("daily_safety_doc", "")

with st.form("daily_safety_form"):
    col1, col2, col3 = st.columns(3)
    with col1:
        briefing_date = st.date_input("Date", value=date.today())
    with col2:
        site_zone = st.text_input("Site / zone", placeholder="e.g. Zone 3 — crane platform")
    with col3:
        crew_size = st.number_input("Crew size", min_value=0, step=1, value=0)

    col4, col5 = st.columns(2)
    with col4:
        weather = st.text_input(
            "Weather conditions",
            placeholder="e.g. Sunny, 32°C, light wind",
        )
    with col5:
        equipment = st.multiselect("Equipment on site today", EQUIPMENT_OPTIONS)
        other_equipment = st.text_input("Other equipment (not listed above)", placeholder="optional")

    activities = st.text_area(
        "Planned activities today",
        placeholder="e.g. Subgrade compaction in Zone 3, geocell panel placement and pinning",
    )
    known_hazards = st.text_area(
        "Known/site-specific hazards today (optional)",
        placeholder="e.g. Open excavation 5m from Zone 3, ground still wet from yesterday's rain",
    )
    platform_note = st.text_input(
        "Platform-specific item to flag (optional)",
        placeholder="e.g. current exclusion zone, an open hold — leave blank if none",
    )

    submitted = st.form_submit_button("Generate daily safety document", icon=":material/auto_awesome:")

if submitted:
    if not activities.strip():
        st.warning("Enter at least the planned activities so the briefing is specific to today.")
    else:
        equipment_list = equipment + ([other_equipment] if other_equipment.strip() else [])
        prompt_lines = [
            "Draft today's daily safety document / toolbox talk using the structure in your "
            "instructions. Here is today's information — use exactly what's given, and mark "
            "anything not provided (e.g. emergency contacts) as a placeholder for the site to "
            "complete, per your own rules:",
            f"- Date: {briefing_date.isoformat()}",
            f"- Site/zone: {site_zone or '[not given]'}",
            f"- Crew size: {crew_size if crew_size else '[not given]'}",
            f"- Weather: {weather or '[not given]'}",
            f"- Equipment on site: {', '.join(equipment_list) if equipment_list else '[not given]'}",
            f"- Planned activities: {activities}",
        ]
        if known_hazards.strip():
            prompt_lines.append(f"- Known/site-specific hazards today: {known_hazards}")
        if platform_note.strip():
            prompt_lines.append(
                f"- Platform-specific item to flag (cross-reference platform-safety framing, "
                f"do not compute a new figure): {platform_note}"
            )
        prompt = "\n".join(prompt_lines)

        api_key = llm.get_api_key()
        with st.chat_message("assistant", avatar=AGENTS[AGENT_KEY]["icon"]):
            st.caption(f"**{AGENTS[AGENT_KEY]['label']}**")
            full_text = st.write_stream(
                llm.stream_agent_reply(AGENT_KEY, [{"role": "user", "content": prompt}], api_key)
            )
        st.session_state.daily_safety_doc = full_text

if st.session_state.daily_safety_doc:
    st.divider()
    st.markdown("### Generated document")
    st.markdown(st.session_state.daily_safety_doc)

    with st.expander("Save as draft record", icon=":material/save:"):
        with st.form("save_daily_safety"):
            category = st.selectbox(
                "Category", RECORD_CATEGORIES, index=RECORD_CATEGORIES.index("daily-safety")
            )
            default_name = f"daily-safety-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}"
            filename = st.text_input("Filename (no extension)", value=default_name)
            draft_banner = (
                "> **STATUS: DRAFT — PENDING RESPONSIBLE ENGINEER'S REVIEW AND SIGN-OFF**\n"
                f"> Generated by the Site Safety daily-document tool "
                f"({datetime.now(timezone.utc).strftime('%Y-%m-%d')}). Not an approved record.\n\n"
            )
            content = st.text_area(
                "Content (editable before saving)",
                value=draft_banner + st.session_state.daily_safety_doc,
                height=300,
            )
            if st.form_submit_button("Save draft", icon=":material/save:"):
                target_dir = RECORDS_DIR / category
                target_dir.mkdir(parents=True, exist_ok=True)
                target_path = target_dir / f"{filename}.md"
                if target_path.exists():
                    target_path = target_dir / f"{filename}-{datetime.now(timezone.utc).strftime('%H%M%S')}.md"
                target_path.write_text(content, encoding="utf-8")
                st.success(f"Saved to `{target_path.relative_to(RECORDS_DIR.parent)}`")
